flags = -Wall -Werror -Wextra -pedantic

2_1Test: 2_1.c 2_1.h
	gcc $(flags) 2_1.c -o 2_1Output
	
	
2_2Test: 2_2.c 2_2.h
	gcc $(flags) 2_2.c -o 2_2Output
	
	
2_3Test: 2_3.c 2_3.h
	gcc $(flags) 2_3.c -o 2_3Output
	

2_4Test: 2_4.c 2_4.h
	gcc $(flags) 2_4.c -o 2_4Output
	