flags = -Wall -Werror -Wextra -pedantic -g

1Test: 1.c 1.h
	gcc $(flags) 1.c -o 1Output
	
2Test: 2.c 2.h
	gcc $(flags) 2.c -o 2Output
	
3Test: 3.c 3.h
	gcc $(flags) 3.c -o 3Output
	
4Test: 4.c 4.h
	gcc $(flags) 4.c -o 4Output